name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: spring-io/spring-gradle-build-action@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set chmod +x
        run: chmod +x ./gradlew
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
